### ISSUE TITLE
파일 정보 가져오기 코드 작성

### ISSUE THREAD

**Issue by seyeon326** [jeong9823/Project2#11]
filestat1, filestat2 함수 작성 부분입니다

**Comment by seyeon326** [comment]
void filestat1(){
    stat("text1", &stat1);	
}

void filestat2(){
    stat("text2", &stat2);
}

해당 경로의 파일 정보를 stat 구조체에 저장하는 함수입니다.

**Comment by jeong9823** [comment]
확인했습니다.

**Comment by Izar111** [comment]
확인했습니다.

**Comment by lllminsuk** [comment]
좋습니다

**Comment by Izar111** [comment]
확인했습니다.
