### ISSUE TITLE
파일 정보 가져오기 코드 리뷰

### ISSUE THREAD

**Issue by seyeon326** [jeong9823/Project2#14]
함수 구현 후 코드 리뷰입니다

**Comment by seyeon326** [comment]
![image](https://user-images.githubusercontent.com/89377951/167674463-5b9a38cc-4d0b-464f-ac81-268fd6639d15.png)

각 파일의 inode 정보가 잘 출력되는 것을 확인할 수 있습니다

**Comment by Izar111** [comment]
문제 없네요. 확인했습니다.

**Comment by jeong9823** [comment]
확인했습니다.

**Comment by lllminsuk** [comment]
유익한 정보네요

**Comment by lllminsuk** [comment]
좋습니다
