### ISSUE TITLE
기반 기술 조사

### ISSUE THREAD

**Issue by jeong9823** [jeong9823/Project2#18]
파일의 수정 시간 정보를 담고 있는 stat 구조체의 m_time을 활용한다. 
2개 파일의 날짜를 비교해야 하므로 해당 구조체의 m_time을 time_t로 가공시켜주는 함수인 localtime()함수를 사용한다.
시간을 나타내는 구조체인 tm에서 사용할 시간 정보는 아래와 같다.
struct tm {
  int tm_mday;  일 [1 ~ 31]
  int tm_mon;   월 [0 ~ 11]
  int tm_year;    년 [1900년 이후]
};

월을 나타내는 tm_mon의 범위는 0부터 11까지이므로 정확한 월을 나타내기 위해선 +1을, 년을 나타내는 tm_year는 1900년에서부터 현재 까지의 차이를 나타내므로 정확한 년도를 나타내기 위해선 +1900을 해주어야 한다.

**Comment by seyeon326** [comment]
아하~ 감사합니다

**Comment by Izar111** [comment]
정보 확인했습니다.

**Comment by lllminsuk** [comment]
유익한 정보네요
