### ISSUE TITLE
sizecmp 코드 리뷰

### ISSUE THREAD

**Issue by lllminsuk** [jeong9823/Project2#19]
완성된 sizecmp 함수에 대한 리뷰 입니다.

**Comment by lllminsuk** [comment]
![image](https://user-images.githubusercontent.com/71426612/167678323-b7e1dcd3-521d-4c3e-9fad-7e73ab5afd37.png)
![image](https://user-images.githubusercontent.com/71426612/167678260-ada221ae-544c-4476-b9a2-ec000258915f.png)
![image](https://user-images.githubusercontent.com/71426612/167678434-28a40b6a-71be-4b8c-a79e-b65bb3a0f632.png)
결과 입니다

**Comment by jeong9823** [comment]
확인했습니다.

**Comment by Izar111** [comment]
작동 확인했습니다

**Comment by seyeon326** [comment]
수고하셨습니다
