### ISSUE TITLE
datecmp function 코드

### ISSUE THREAD

**Issue by jeong9823** [jeong9823/Project2#20]
void datecmp() {
    int tm2 = ((time2->tm_year + 1900) * 100 + (time2->tm_mon + 1) * 100) + time2->tm_mday;
    time1 = localtime(&stat1.st_mtime);
    int tm1 = ((time1->tm_year + 1900) * 100 + (time1->tm_mon + 1) * 100) + time1->tm_mday;
    printf("date compare\n");
    if (tm1 > tm2) printf("text2 is early\n\n");
    else if (tm1 < tm2) printf("text1 is early\n\n");
    else printf("same time\n\n");
}

**Comment by seyeon326** [comment]
좋습니다 ~

**Comment by Izar111** [comment]
확인했습니다.

**Comment by lllminsuk** [comment]
좋습니다
