### ISSUE TITLE
기반 기술 조사

### ISSUE THREAD

**Issue by jeong9823** [jeong9823/Project2#21]
파일의 수정 시간 정보를 담고 있는 stat 구조체의 m_time을 활용한다.
2개 파일의 날짜를 비교해야 하므로 해당 구조체의 m_time을 time_t로 가공시켜주는 함수인 localtime()함수를 사용한다.
시간을 나타내는 구조체인 tm에서 사용할 시간 정보는 아래와 같다.
struct tm {
  int tm_sec;   초 [0 ~ 61]
  int tm_min;  분 [0 ~ 59]
  int tm_hour; 시 [0 ~ 23]
};

**Comment by seyeon326** [comment]
좋은 정보 감사합니다

**Comment by Izar111** [comment]
정보 감사합니다.

**Comment by lllminsuk** [comment]
유익하네요
