### ISSUE TITLE
파일 시간 받아 오기 코드리뷰

### ISSUE THREAD

**Issue by Izar111** [jeong9823/Project2#23]
filetime1, filetime2 함수에서 tm structure의 날짜와 시간을 임의로 출력
------------------------------------------------------------------------------------------

> void filetime1(){
>     time1 = localtime(&stat1.st_mtime);
>     printf("text1 time --> %d . %d . %d   %d : %d : %d \n",1900+time1->tm_year,time1->tm_mon,time1->tm_mday,time1->tm_hour,time1->tm_min,time1->tm_sec);
> }
> 
>  
>  void filetime2(){
>      time2 = localtime(&stat2.st_mtime);
>      printf("text2 time --> %d . %d . %d   %d : %d : %d \n",1900+time2->tm_year,time2->tm_mon,time2->tm_mday,time2->tm_hour,time2->tm_min,time2->tm_sec);
> }
> 

---------------------------------------------------------------------------------------------
아래와 같이 각 파일의 수정 시간이 ls 와 동일하게 출력 되는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/34090234/167677357-96a329db-4391-42cd-8cf7-04d55ab52ee4.png)

![image](https://user-images.githubusercontent.com/34090234/167677918-0375dfcb-14c8-4e36-8b79-80ff89682afa.png)

**Comment by seyeon326** [comment]
수고하셨습니다 ~

**Comment by jeong9823** [comment]
고생했습니다.

**Comment by lllminsuk** [comment]
좋습니다
