### ISSUE TITLE
blockcmp 기술 조사

### ISSUE THREAD

**Issue by lllminsuk** [jeong9823/Project2#25]
블락 크기를 비교하는 blockcmp 함수 구현에 사용될 기술 조사 입니다.

**Comment by lllminsuk** [comment]
int stat 함수를 사용하여 stat 구조체에 파일의 정보를 받아올 수 있는데, 이 중 st_blocks 변수에는 블락 크기 정보가 저장되어 있습니다.

**Comment by jeong9823** [comment]
확인했습니다.

**Comment by seyeon326** [comment]
네 알겠습니다~

**Comment by Izar111** [comment]
정보 확인했습니다.
