### ISSUE TITLE
파일 시간 받아오기 기술 조사

### ISSUE THREAD

**Issue by Izar111** [jeong9823/Project2#3]
sys/types.h에 정의된 tm structure를 이용하여 시간 데이터 저장.    
localtime 함수를 이용하여 stat structure에 time_t 변수로 저장된 시간을 tm structure로 변경하여 저장한다.

**Comment by seyeon326** [comment]
넵 감사합니다

**Comment by Izar111** [comment]
tm structure 구조입니다.

struct tm {
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};

**Comment by seyeon326** [comment]
넵 감사합니다

**Comment by jeong9823** [comment]
네 확인했습니다.

**Comment by lllminsuk** [comment]
좋네요
