### ISSUE TITLE
파일 수정시간(시/분) 비교 함수 issue

### ISSUE THREAD

**Issue by jeong9823** [jeong9823/Project2#6]
void timecmp() {
	stat("text1", &stat1);
	stat("text2", &stat2);
	time1 = localtime(&stat1.st_mtime);
	time2 = localtime(&stat2.st_mtime);
	int tm1 = (time1->tm_hour * 100) + time1->tm_min;
	int tm2 = (time2->tm_hour * 100) + time2->tm_min;
	printf("%d, %d\n%d, %d\n", time1->tm_hour,time1->tm_min, time2->tm_hour, time2->tm_min);
	printf("time compare\n");
	if (tm1 > tm2) printf("text2 is early\n\n");
	else if (tm1 < tm2) printf("text1 is early\n\n");
	else printf("same time\n\n");
}

해당 함수를 컴파일 하면 각각 다른 파일에 대한 시간 정보가 뜨는게 아니라 text2의 파일 시간 정보만 불러와집니다. 해당 코드에 오류는 없는거 같은데 무엇이 문제일까요??

**Comment by Izar111** [comment]
확인했습니다.

**Comment by Izar111** [comment]
time1 = localtime(&stat1.st_mtime);
int tm1 = (time1->tm_hour * 100) + time1->tm_min;
time2 = localtime(&stat2.st_mtime);
int tm2 = (time2->tm_hour * 100) + time2->tm_min;

으로 하면 바뀌기 전에 변수에 저장되어서 문제 없습니다.

**Comment by lllminsuk** [comment]
위 코드에서 4번째 줄이랑 5번째 줄 순서를 바꿨더니 text1의 파일 시간 정보만 가져오네요

**Comment by seyeon326** [comment]
해결하느라 고생하셨습니다

**Comment by jeong9823** [comment]
void timecmp(){
    int tm1 = ((time1->tm_hour * 100) + time1->tm_min) * 100 + time1->tm_sec;
    time2 = localtime(&stat2.st_mtime);
    int tm2 = ((time2->tm_hour * 100) + time2->tm_min) * 100 + time2->tm_sec;
    printf("time compare\n");
    if (tm1 > tm2) printf("text2 is early\n\n");
    else if (tm1 < tm2) printf("text1 is early\n\n");
    else printf("same time\n\n");
}
코드를 위와 같이 변경하여 수정하였습니다. 감사합니다
