### ISSUE TITLE
파일 시간 받아 오기 코드작성

### ISSUE THREAD

**Issue by Izar111** [jeong9823/Project2#7]
void filetime1(){
    time1 = loacltime(&stat1.st_mtime);
}

void filetime2(){
    time2 = loacltime(&stat2.st_mtime);
}

**Comment by lllminsuk** [comment]
굿입니다~

**Comment by Izar111** [comment]
오탈자 확인되어 수정되었습니다.  
void filetime1(){
time1 = localtime(&stat1.st_mtime);
}

void filetime2(){
time2 = localtime(&stat2.st_mtime);
}

**Comment by seyeon326** [comment]
좋네요 :)

**Comment by jeong9823** [comment]
확인했습니다.
